[package]
name = "yt_tutorial_projects"
version = "0.1.0"
edition = "2024"

[dependencies]
panic-halt = "1.0.0"

[dependencies.arduino-hal]
git="https://github.com/Rahix/avr-hal" 
features = ["arduino-uno"]
