[build]
target="avr-none"
rustflags=["-C","target-cpu=atmega328p"]


[target.'cfg(target_arch="avr")']
runner= "./run.sh"

[unstable]
build-std=["core"]

[profile.dev]
opt-level="s"
panic="abort"
lto=true

[profile.release]
opt-level="s"
panic="abort"
lto=true
debug=true
codegen-units=1

[alias]
rr = "run --release"
